# Generated by Django 4.1.4 on 2026-01-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.UUIDField()),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro(a)')], default=None, max_length=50)),
                ('degree', models.CharField(choices=[('fundamental', 'Fundamental completo'), ('fundamental_na', 'Fundamental incompleto'), ('high_school', 'Ensino medio completo'), ('high_school_na', 'Ensino medio incompleto'), ('graduation', 'Superior completo'), ('graduation_na', 'Superio incompleto'), ('other', 'Outro')], default=None, max_length=50)),
                ('contact_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('relationship', models.CharField(choices=[('father', 'Pai'), ('mother', 'Mae'), ('other', 'Outro')], default=None, max_length=50)),
            ],
            options={
                'verbose_name': 'Registration',
            },
        ),
    ]
